AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TestServer:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      ImageId: ami-0bba69335379e17f8
      InstanceType: t2.micro
