AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TestServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bba69335379e17f8
      InstanceType: t2.micro
      KeyName: redis-client
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: 0
        GroupSet: 
          - !Ref TestServerSecurityGroup
        SubnetId: subnet-0df8ac1e84023a09b
  TestServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: TestServerSecurityGroup
      GroupName: TestServerSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: vpc-0788cef103e65d889
      Tags:
        - Key: Name
          Value: TestServerSecurityGroup
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - subnet-0df8ac1e84023a09b
        - subnet-03f2dea888604b427
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: ALBSecurityGroup
      GroupName: ALBSecurityGroup
      SecurityGroupIngress: 
        - SourceSecurityGroupId: !Ref TestServerSecurityGroup
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      VpcId: vpc-0788cef103e65d889
      Tags:
        - Key: Name
          Value: ALBSecurityGroup
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Host: !Select ['1', !Split [':', !Select ['0', !GetAtt VpcEndpoint.DnsEntries]]]
            Path: /web-deploy-zhbing/1.txt
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301
      LoadBalancerArn: !Ref ALB
      Certificates:
        - CertificateArn: arn:aws:acm:ap-northeast-1:977565376628:certificate/56bff2ba-9432-4b17-98c5-46348a054f4d
  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: VpcEndpointSecurityGroup
      GroupName: VpcEndpointSecurityGroup
      SecurityGroupIngress: 
        - SourceSecurityGroupId: !Ref TestServerSecurityGroup # ALBSecurityGroup tested, NG
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      VpcId: vpc-0788cef103e65d889
      Tags:
        - Key: Name
          Value: VpcEndpointSecurityGroup
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      ServiceName: com.amazonaws.ap-northeast-1.s3
      SubnetIds:
        - subnet-0df8ac1e84023a09b
        - subnet-03f2dea888604b427
      VpcEndpointType: Interface
      VpcId: vpc-0788cef103e65d889
